name: ci-translate

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  ci-translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      cache-hit: ${{ steps.translate-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Checkout translate-dm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          repository: iam-akuzihs/translate-dm
          path: git/translate-dm

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        id: nix-cache
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix', 'flake.lock') }}
      - name: Prefetch nix shell
        if: steps.nix-cache.outputs.hit-primary-key != 'true'
        run: nix develop -c true

      - name: Setup go cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup translate cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: translate-cache
        with:
          path: ~/checksum
          key: checksum-${{ hashFiles('checkout.mk', 'git/translate-dm/**', '!**/.git', '!**/queries/*.yml') }}-${{ hashFiles('**/queries/*.yml') }}
          restore-keys: |
            checksum-${{ hashFiles('checkout.mk', 'git/translate-dm/**', '!**/.git', '!**/queries/*.yml') }}-

      - name: Run ci-translate
        if: steps.translate-cache.outputs.cache-hit != 'true'
        run: |
          set -eu

          mv git/translate-dm ..
          rm -d git

          [ -e "$HOME/checksum" ] && sha256sum --check -- "$HOME/checksum" && exit 0
          sha256sum ../translate-dm/queries/binout.yml > "$HOME/checksum"

          nix develop -c make TRANSLATE_DM=../translate-dm translate 2> /dev/null
          git push origin master

  ci-rebuild:
    runs-on: ubuntu-latest
    needs: [ci-translate]
    if: needs.ci-translate.outputs.cache-hit != 'true'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: master

      - name: Rebuild live branch
        run: |
          set -eu

          make rebuild
          git push -f origin live
